name: ui_bits
description: A UI components(bits) library
version: 0.0.11

homepage: https://github.com/AlienEngineer/ui-bits

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  loading: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.0.0

flutter:

  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
