name: ui_bits
description: A UI components(bits) library
version: 0.0.36

homepage: https://github.com/AlienEngineer/ui-bits

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  loading: ^1.0.2
  font_awesome_flutter: ^9.0.0
  intl: ^0.17.0
  syncfusion_flutter_calendar: ^19.1.54+1
  syncfusion_localizations: ^19.1.54+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
  equatable: ^2.0.0

flutter:

  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
