name: ui_bits
description: A UI components(bits) library
version: 0.0.31

homepage: https://github.com/AlienEngineer/ui-bits

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  loading: ^1.0.2
  font_awesome_flutter: ^8.11.0
  intl: ^0.16.0
  syncfusion_flutter_calendar: ^18.4.47
  syncfusion_localizations: ^18.1.36

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.2
  equatable: ^1.2.5

flutter:

  fonts:
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
