name: Build

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bump versions
        run: ./bump-version.sh

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump Version
          commit_user_name: org-bot

  format-code:
    runs-on: ubuntu-latest
    needs: [ bump-version ]

    container:
      image: cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - name: Format code
        run: flutter format .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format code

  build:
    runs-on: ubuntu-latest
    needs: [ format-code ]

    container:
      image:  cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
