name: Flutter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image:  cirrusci/flutter:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Publish package
        run: pub publish -f
        if: contains('refs/heads/master', github.ref)
