name: Flutter

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Publish package
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        if: contains('refs/heads/master', github.ref)
        with:
          credential: ${{ secrets.PACKAGE_CREDENTIAL_JSON }}
